### ISSUE TITLE
Remove unnecessary MPI buf allocation

### ISSUE THREAD

**Issue by herjmoo** [intel/yask#188]
Need to fix allocMpiData pass not to allocate MPI buffer for constant grids.

*Replicate recipe*
make -j arch=skx stencil=fsg YK_CXXOPT='-O0' EXTRA_MACROS='CHECK TRACE'
bin/yask.sh -stencil fsg -arch skx -ranks 2 -dx 512 -dy 512 -dz 512 -dt 50 -t 1 -thread_divisor 1 -block_threads 2 -no-pre_auto_tune

YASK:   MPI buf 'c11_recv_halo_from_1_to_0' needs 4.03912MiB using mem-key -1
YASK:   MPI buf 'c12_recv_halo_from_1_to_0' needs 4.03912MiB using mem-key -1
...

c** is constant grid.

**Comment by chuckyount** [comment]
It turns out that these constant grids actually do need MPI buffers because multiple points from them are read for each computation. Only receive buffers are allocated in rank 0 because the points are only read from the right side, so rank 0 doesn't need send buffers.
Made some small changes to improve the trace messages in v2.16.04. Will close when that version is merged into `master`.
